const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const a=process.argv[2],bfile=process.argv[3];
assert(a && bfile,'Provide two different readable HWPX files');
function check(label,ok){assert(ok,label);console.log('PASS',label);}
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage(); const url=require('node:url').pathToFileURL(require('node:path').resolve(__dirname,'../index.html')).href;
await p.goto(url);await p.locator('#fileInput').setInputFiles(a);await p.waitForFunction(()=>document.querySelectorAll('.hx-pagecard').length);const count=await p.locator('.hx-pagecard').count();
await p.locator('#fileInput').setInputFiles({name:'broken.ttf',mimeType:'font/ttf',buffer:Buffer.from('invalid')});await p.waitForTimeout(250);check('font-failure-keeps-document',await p.locator('.hx-pagecard').count()===count);
await p.reload();await p.evaluate(()=>{const fn=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){if(this.name==='slow.ttf')await new Promise(r=>setTimeout(r,500));return fn.call(this)}});
await p.locator('#fileInput').setInputFiles([{name:'slow.ttf',mimeType:'font/ttf',buffer:Buffer.from('invalid')},{name:'old.hwpx',mimeType:'application/zip',buffer:require('fs').readFileSync(a)}]);await p.waitForTimeout(50);await p.locator('#fileInput').setInputFiles(bfile);await p.waitForTimeout(1200);check('latest-selection-wins',(await p.locator('#fname').textContent()).includes(require('node:path').basename(bfile)));
await p.reload();await p.locator('#fileInput').setInputFiles([a,bfile]);await p.waitForFunction(()=>document.querySelectorAll('.hx-pagecard').length);await p.locator('#btnReset').click();await p.waitForTimeout(850);check('reset-keeps-filename-clear',(await p.locator('#fname').textContent())==='');
const cleanup=await p.evaluate(()=>{const enc=s=>new TextEncoder().encode(s);const files={'Contents/header.xml':enc('<head/>'),'Contents/section0.xml':enc('<sec><p><run><pic><img binaryItemIDRef="image1"/></pic></run></p></sec>'),'Contents/section1.xml':enc('<bad'),'BinData/image1.png':new Uint8Array([1])};let created=[],revoked=[];const c=URL.createObjectURL,r=URL.revokeObjectURL;URL.createObjectURL=x=>{const u=c(x);created.push(u);return u};URL.revokeObjectURL=x=>{revoked.push(x);r(x)};let error;try{HWPViewer.Hwpx.render(files,document.createElement('div'),document)}catch(e){error=e.message}finally{URL.createObjectURL=c;URL.revokeObjectURL=r}return {created:created.length,revoked:revoked.length,error}});assert.equal(cleanup.created,1);assert.equal(cleanup.revoked,1);assert.match(cleanup.error,/XML/);console.log('PASS image-cleanup');
}finally{await b.close()}})().catch(error=>{console.error(error);process.exitCode=1});
